### ISSUE TITLE
yarn run bsb -make-world -w not work

### ISSUE THREAD

**Issue by robbinhan** [turakuapp/turaku-client#13]
I follow thi step 
```bash

yarn install
yarn run tailwind build src/tailwind/index.css -o src/index.css
yarn run start
```
then open browser on http://localhost:3000, but it's blank page, nothing.

then I run 
```bash
yarn run bsb -make-world -w
```

it's report error
```txt
[6/25] Building src/components/SignUpMenu.mlast
Read_schema.Schema_file_not_found

  We've found a bug for you!
  /Users/robbin/code/turaku-client/src/components/SignUpMenu.re

  There's been an error running a preprocessor before the compilation of a file.
  This was the command:

  /Users/robbin/code/turaku-client/node_modules/graphql_ppx/ppx '/var/folders/4m/mffx801x0tdgnr8y55sqsgkh0000gn/T/camlppxb1223c' '/var/folders/4m/mffx801x0tdgnr8y55sqsgkh0000gn/T/camlppx369027'

[7/25] Building src/components/TeamMenu.mlast
Read_schema.Schema_file_not_found

  We've found a bug for you!
  /Users/robbin/code/turaku-client/src/components/TeamMenu.re

  There's been an error running a preprocessor before the compilation of a file.
  This was the command:

  /Users/robbin/code/turaku-client/node_modules/graphql_ppx/ppx '/var/folders/4m/mffx801x0tdgnr8y55sqsgkh0000gn/T/camlppx5c5e93' '/var/folders/4m/mffx801x0tdgnr8y55sqsgkh0000gn/T/camlppxf57ee3'

[8/25] Building src/components/SaveNowButton.mlast
Read_schema.Schema_file_not_found

  We've found a bug for you!
  /Users/robbin/code/turaku-client/src/components/SaveNowButton.re

  There's been an error running a preprocessor before the compilation of a file.
  This was the command:

  /Users/robbin/code/turaku-client/node_modules/graphql_ppx/ppx '/var/folders/4m/mffx801x0tdgnr8y55sqsgkh0000gn/T/camlppxb9469b' '/var/folders/4m/mffx801x0tdgnr8y55sqsgkh0000gn/T/camlppx548a7b'

[9/25] Building src/components/SignInMenu.mlast
Read_schema.Schema_file_not_found

  We've found a bug for you!
  /Users/robbin/code/turaku-client/src/components/SignInMenu.re

  There's been an error running a preprocessor before the compilation of a file.
  This was the command:

  /Users/robbin/code/turaku-client/node_modules/graphql_ppx/ppx '/var/folders/4m/mffx801x0tdgnr8y55sqsgkh0000gn/T/camlppxe9b5b4' '/var/folders/4m/mffx801x0tdgnr8y55sqsgkh0000gn/T/camlppxa3348e'

[10/25] Building src/components/TeamSelection.mlast
Read_schema.Schema_file_not_found

  We've found a bug for you!
  /Users/robbin/code/turaku-client/src/components/TeamSelection.re

  There's been an error running a preprocessor before the compilation of a file.
  This was the command:

  /Users/robbin/code/turaku-client/node_modules/graphql_ppx/ppx '/var/folders/4m/mffx801x0tdgnr8y55sqsgkh0000gn/T/camlppx46f77b' '/var/folders/4m/mffx801x0tdgnr8y55sqsgkh0000gn/T/camlppxf3ab73'

ninja: error: rebuilding 'build.ninja': subcommand failed
>>>> Finish compiling(exit: 1)
```

so I don't know how to run

**Comment by harigopal** [comment]
Hello Robbin! The documentation for this repo is out-of-date - the setup instruction are from back when the [server](https://github.com/turakuapp/turaku-client) still had a RESTful API. I've switched to GraphQL since then, and the client repo now requires a local copy of the GraphQL schema to compile.

To fetch one, you'll need a running [server](https://github.com/turakuapp/turaku-client) on your localhost.

I'll update documentation for the repo later, but may I know why you're interested in Turaku? This software is definitely _not_ ready for use. In fact, **the client does not compile right now**, because I'd made some changes to the GraphQL schema last week that I haven't gotten around to updating on the client.

**Comment by robbinhan** [comment]
Hi harigopal, Thank for your response. I interested in Turaku because I watched your this [keynote](https://www.youtube.com/watch?v=3tWExsIae8g) , and I want learn reasonml; so I hope this project will help me to learn it.

**Comment by harigopal** [comment]
@robbinhan I've expanded the set up instructions of this repo to make it explicit that the client expects the server to be running on localhost, and I've also included the step specifying how to download the GraphQL schema from the running server.

I've also fixed all errors blocking compilation. I'm closing this issue since the error you mentioned arose from poor documentation.

If you're just getting started with ReasonML, I highly recommend going through the [Learn ReasonML workshop](https://github.com/protoship/learn-reasonml-workshop)! ✌️
